---
title: "Introduction to GenErlang Fit"
author: "Vivek Murali"
output: 
  rmarkdown::html_vignette:
    toc: true
    

vignette: >
  %\VignetteIndexEntry{Introduction to GenErlang Fit}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



```{css, echo=FALSE}
body {
  text-align: justify;
}


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Context and Package Overview

The GenErlangFit package aims to identify the optimal generalized Erlang or Erlang–Exponential model consistent with observed time-to-event data.

Standard compartmental models of infectious diseases often assume constant transition rates between states, which implies an exponential distribution of “waiting times” in each state. (e.g., the latent period, the infectious period). However, this assumption does not align with empirical data for many diseases. The Linear Chain Trick (LCT) offers a computationally tractable alternative by modeling each state as a series of multiple identical substates, producing Erlang-distributed waiting times (Gamma distribution with an integer shape parameter). 

Our approach combines maximum likelihood parameter estimation with non-parametric significance testing to prioritize the simplest model structures that produce waiting times consistent with observed data. To improve flexibility, we incorporate the Erlang-Exponential model—an extension of the standard Erlang distribution that adds a final exponential stage— allowing better approximation of empirical distributions with varying skewness and tail behavior. 

This user-friendly package enables modelers to fit empirical data and build parsimonious, data-driven compartmental models across diverse domains. A thorough walk through of the fitting algorithms and assumptions can be found in the [**FAQ vignette linked here**](FAQ.html). This vignette serves as simple tutorial on how users can get started with this package. 

---

# Package Installation from Github

To install and load the package from GitHub, run these commands in the R console and load the following libraries:

```r
devtools::install_github("vivekmurals/GenErlangFit")
library(GenErlangFit)
library(ggplot2)

```

---

# Using the Package

## Data Format

Before fitting, the input `empiricaldata` must be provided as a single numeric vector of observed time-to-event values, with all entries strictly positive. If your data are stored in a CSV file with a column named Time, you can load them using:

```r
empiricaldata <- c(1.2, 3.4, 2.1, 5.6, 4.3)

# or loaded from a file:
empiricaldata <- read.csv("mydata.csv")$Time

```

## General Fitting under Default Settings

In general, the user only needs to be familiar using one single function `GenErlang_Fit`. By default, if the user runs the following line of code with `empiricaldata` as the only argument, 

```r
GenErlang_Fit(empiricaldata)

```
the function will run both the Erlang and Erlang-Exp fit, run goodness of fit evaluations for both and in addition, search for the smallest statistically acceptable K for both models. More on what the smallest K model means can be found in [**FAQ: Smallest K Model**](FAQ.html#smallest-k). 

Users also have the ability to choose the specific model they would like to fit the data to via specifying the following input arguments:

```r
GenErlang_Fit('Erlang', empiricaldata)
GenErlang_Fit('ErlangExp', empiricaldata, K)

```
**Quick Note:** When running specific models, the model name must always be provided as the first argument. For the Erlang-Exponential model, an additional input argument K must always be provided since the search for the optimal K is handled differently from that of the Erlang. See [**FAQ: Erlang-Exp Fit**](FAQ.html#erlangexp-k).

While these default modes are designed to be comprehensive and is generally the best starting point for first-time users, those who prefer a quicker initial exploration may first run the Erlang model alone to get a broad sense of the empirical data’s structure.

### Outputs from GenErlang_Fit 

The object returned by GenErlang_Fit is a structured list that organizes all results produced during the fitting procedure. For example, after running:

```r
Results <- GenErlang_Fit('Erlang', empiricaldata)

```
the main components of the output— `Results$BestFit` and `Results$SmallestK` — contain the corresponding fitted model summaries. Each of these components includes the estimated model parameters, the log-likelihood, the goodness-of-fit quantities, and summary statistics used in the evaluation. 

---

## Model Specific Fitting Options 

Once users are familiar with the default behavior of `GenErlang_Fit`, users can proceed onto learning how to customize different aspects the fitting workflow. The following sections outline the main categories of options available when departing from the default settings: Fit Options (e.g., changing initial guesses or controlling the Erlang-exp search over K), Goodness-of-Fit Options (e.g., bootstrap-based confidence intervals and p-value estimation), and the Smallest-K Search tools used for model parsimony or computational efficiency. Each subsection explains the purpose of these options, how to call them, and in what situations users may want to override the defaults.

### Overriding initial guesses  
GenErlang_Fit provides default initialization values for all optimization routines. Users may optionally supply their own initial guesses to customize the fitting process or to assess the robustness of results to different starting values. 
```r
GenErlang_Fit('Erlang', empiricaldata, 'InitialguessK = VALUE')
GenErlang_Fit('ErlangExp', empiricaldata, K, 'InitialguessErlam = VALUE')

```
 - Erlang model: the initial guess refers to the Erlang shape parameter, K used during optimization.

 - Erlang–Exponential model: the initial guess refers to the Erlang rate parameter 𝜆 because K is provided explicitly by the user.

### Additional Erlang-Exp Fitting Option  
For the Erlang–Exponential model, the input parameter K plays a dual role depending on user settings: it can either be treated as a fixed shape parameter for which the maximum likelihood estimate is computed directly, or it can serve as the central value around which the function searches a range of nearby K values to identify a better-fitting model structure.

```r
GenErlang_Fit('ErlangExp', empiricaldata, K, FixedK = TRUE)
GenErlang_Fit('ErlangExp', empiricaldata, K, FixedK = FALSE, KwindowSize = VALUE)

```
When FixedK = TRUE, the function performs a pure MLE fit for the given K, using any supplied initial conditions.
When FixedK = FALSE, the function expands the search to include K ± a user-defined window (KwindowSize), rendering initial guess overrides less relevant because the optimization is repeated across multiple candidate structures.THis is the default option when FixedK argument is not provided.

## Goodness of Fit Options
GenErlang_Fit provides built-in tools for assessing how well each fitted model matches the empirical distribution. These options apply to both Erlang and Erlang–Exp models and include:

- Choice of test statistic (via `pvaloption`)
- Significance level (`Alpha`)
- Number of bootstrap samples (`NumBootStraps`)

A detailed description on how the goodness of fit of a model is evaluated can be found here: [**FAQ: Goodness of Fit Evaluation**](FAQ.html#gof).

### Overriding choice of Test Statistic 

Users can select which distance measure to use in evaluating the model's goodness-of-fit. Available options are: 

- "KS" — Kolmogorov–Smirnov Statistic
- "CVM" — Cramér–von Mises Statistic
- "AD" — Anderson–Darling Statistic
- "NIL" — skips evaluation entirely and just performs the model fit

Users can specify the test statistic by providing the `pvaloption` argument as follows:

```r
GenErlang_Fit('Erlang', empiricaldata, pvaloption = 'KS')
GenErlang_Fit('ErlangExp', empiricaldata, K, pvaloption = 'NIL')

```

### Overriding choice of Alpha 

The argument `Alpha` determines the significance level (rejection threshold) used when evaluating the bootstrap test statistics. Smaller values correspond to a more conservative goodness-of-fit assessment.

```r
GenErlang_Fit('Erlang', empiricaldata, Alpha = 0.05)
GenErlang_Fit('ErlangExp', empiricaldata, K, Alpha = 0.01)

```

### Overriding choice of Number of Bootstraps

Increasing the number of bootstrap samples improves the stability and precision of p-value estimates—but also increases runtime. Users can control this by setting the `NumBootStraps` argument to any value of interest as follows:

```r
GenErlang_Fit('Erlang', empiricaldata, NumBootStraps = 10000)
GenErlang_Fit('ErlangExp', empiricaldata, K, NumBootStraps = 2000)

```


## Smallest K Option
The “Smallest-K” routines automatically search for the simplest model that remains statistically consistent with the observed data. Starting from the best-fitting K, the procedure iteratively tests decreasing values of K to identify the smallest value of K that still meets the user's goodness-of-fit criteria (i.e., p > α). A detailed description of this section can be found here: [**FAQ: Smallest K Model**](FAQ.html#smallest-k).

Users can enable the smallest-K search by specifying the `SmallestK` argument as follows:


```r
GenErlang_Fit('Erlang', empiricaldata, SmallestK = TRUE)

GenErlang_Fit('ErlangExp', empiricaldata, K, SmallestK = TRUE)
GenErlang_Fit('ErlangExp', empiricaldata, K, SmallestK = TRUE, SmallestKvalue = VALUE)

```

For Erlang–Exponential models specifically, the optional `SmallestKvalue` sets the starting value of K for the iterative search. This can help reduce computational time if users suspect that the smallest acceptable K is much lower than the best-fitting K. 

---

# Conclusion 

The GenErlangFit package offers a flexible and user-friendly toolkit for fitting generalized Erlang and Erlang–Exponential models to empirical time-to-event data. By identifying the appropriate number of substates (shape parameters) and transition rates, the package helps users build parsimonious compartmental models that more accurately capture the underlying biological or process dynamics.

We encourage users to explore the different fitting options, goodness-of-fit evaluations, and the smallest-K search to tailor the analysis to their specific datasets and research questions. For a deeper dive into the theoretical foundations, algorithmic details, and troubleshooting tips, please consult the [**FAQ vignette linked here**](FAQ.html). 

If you encounter any issues or have suggestions for new features, feel free to open an issue on the [**GitHub repository**](https://github.com/vivekmurals/GenErlangFit/issues).

Thank you for using GenErlangFit and We look forward to seeing how GenErlangFit aids your modeling efforts!
